### ISSUE TITLE
Des soucis avec les toolbox

### ISSUE THREAD

**Issue by leknoppix** [maxpou/docker-symfony#61]
Bonjour

Je suis tombé sur ton dépôt et merci beaucoup.
Je suis arrivé à faire un docker-compose build et up, sans aucun soucis.

Le soucis est que quand je cherche à utiliser une des instructions de toolbox, 'obtiens:
`Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 58, in main
  File "compose\cli\main.py", line 109, in perform_command
  File "compose\cli\main.py", line 348, in exec_command
NameError: global name 'ExecOperation' is not defined
docker-compose returned -1`

Aurais-tu une idée?
Merci d'avance.

**Comment by maxpou** [comment]
in english please...
